//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by resvis.rc
//
#define IDR_MAINFRAME                   10
#define IDI_MIDIFILE                    15
#define IDD_ABOUTBOX                    100
#define IDC_POINTER                     104
#define IDI_WAVFILE                     128
#define IDR_CUIKTYPE                    129
#define IDD_CONFIGDIALOG                129
#define IDD_STATUSBAR                   130
#define IDR_CUIKACCELERATOR             131
#define IDD_MENUBAR                     131
#define IDR_MENU                        132
#define IDD_CONTROLBAR                  132
#define IDD_DIALOG1                     135
#define IDC_VSPLIT                      157
#define IDI_LEVEL                       195
#define IDI_SCENE                       196
#define IDI_PLACE                       197
#define IDI_LIGHT                       198
#define IDI_MESH                        199
#define IDI_FRAME                       200
#define IDI_CAMERA                      201
#define IDI_BEHAVIOR                    202
#define IDI_3DENTITY                    203
#define IDI_MATERIAL                    204
#define IDI_TEXTURE                     205
#define IDI_SPRITE                      206
#define IDI_SPRITE3D                    207
#define IDI_CHARACTER                   208
#define IDI_FILE                        209
#define IDI_DIRECTORY                   210
#define IDI_INMEMORY                    211
#define IDI_GAMEMASTER                  212
#define IDI_UNKNOWN                     213
#define IDI_OBJECT3D                    214
#define IDI_CURVE                       215
#define IDI_CURVEPOINT                  216
#define IDI_EXPAND                      217
#define IDI_TREEEXPAND                  217
#define IDI_EXPANDED                    218
#define IDI_TREEEXPANDED                218
#define IDC_OVEROBJECT                  331
#define IDC_MOVEOBJECT                  332
#define IDC_SCALEOBJECT                 333
#define IDC_ROTATEOBJECT                334
#define IDC_ALIGN                       348
#define IDC_CREATE                      351
#define IDD_EMPTY                       352
#define IDC_ZOOMCAMERA                  352
#define IDD_EDITLINK                    353
#define IDC_ROLLCAMERA                  353
#define IDD_EDITPARAMETER               354
#define IDC_DOLLYCAMERA                 354
#define IDD_CREATEPARAMOP               355
#define IDC_ORBITCAMERA                 355
#define IDD_SAVEBEHAVIOR                356
#define IDC_FOVCAMERA                   356
#define IDD_LOADBEHAVIOR                357
#define IDC_PANCAMERA                   357
#define IDC_GRABHAND                    358
#define IDC_VECTORMOVE                  359
#define IDC_VECTORLINK                  360
#define IDC_VECTORZOOM                  361
#define IDC_VECTORSELECT                362
#define IDC_VECTORDELETE                363
#define IDI_NULL                        373
#define IDI_DEFAULT                     374
#define IDI_GLOBAL                      375
#define IDI_DATABASE                    376
#define IDI_USERBEHAVIOR                379
#define IDI_2DENTITY                    380
#define IDI_SOUND                       382
#define IDI_ANIMATION                   383
#define IDI_GROUP                       384
#define IDI_SHOW                        385
#define IDI_HIDE                        386
#define IDI_HALFHIDE                    387
#define IDI_HALFDISABLE                 388
#define IDI_DISABLE                     389
#define IDI_ENABLE                      390
#define IDI_FOLDER                      392
#define IDI_DROPDOWN                    393
#define IDI_NEMOFILE                    394
#define IDI_3DSFILE                     395
#define IDI_XFILE                       396
#define IDI_NBEHAVIOR                   397
#define IDI_TEXTUREFILE                 398
#define IDI_BIGUNKNOWN                  399
#define IDD_SPLASH                      473
#define IDD_STATICMESSAGE               525
#define IDI_SCRIPT                      526
#define IDI_NEMOBW                      532
#define IDI_IC                          533
#define IDI_BODYPART                    534
#define IDI_LOCALPARAMETER              538
#define IDI_POSTIT                      539
#define IDD_ERROR_LOG2                  572
#define IDD_DELETEOBJECT                573
#define IDB_AADD                        583
#define IDB_AADD2                       584
#define IDB_ALIGN_N                     585
#define IDB_ALIGN_P                     586
#define IDB_ALIGN_R                     587
#define IDB_AMINUS                      588
#define IDB_AMINUS2                     589
#define IDB_AXISX_N                     590
#define IDB_AXISX_P                     591
#define IDB_AXISX_R                     592
#define IDB_AXISXY_N                    593
#define IDB_AXISXY_P                    594
#define IDB_AXISXY_R                    595
#define IDB_AXISY_N                     596
#define IDB_AXISY_P                     597
#define IDB_AXISY_R                     598
#define IDB_AXISYZ_N                    599
#define IDB_AXISYZ_P                    600
#define IDB_AXISYZ_R                    601
#define IDB_AXISZ_N                     602
#define IDB_AXISZ_P                     603
#define IDB_AXISZ_R                     604
#define IDB_AXISZX_N                    605
#define IDB_AXISZX_P                    606
#define IDB_AXISZX_R                    607
#define IDB_BOMB                        608
#define IDB_BOMB1                       608
#define IDB_CHECK_N                     609
#define IDB_CHECK_P                     610
#define IDB_CHECK_R                     611
#define IDB_CHECK_RP                    612
#define IDB_CLOSE_N                     613
#define IDB_CLOSE_P                     614
#define IDB_CREATECAMERA_N              615
#define IDB_CREATECAMERA_P              616
#define IDB_CREATECAMERA_R              617
#define IDB_CREATECURVE_N               618
#define IDB_CREATECURVE_P               619
#define IDB_CREATECURVE_R               620
#define IDB_CREATEFRAME_N               621
#define IDB_CREATEFRAME_R               622
#define IDB_CREATEFRAME_P               623
#define IDB_CREATELIGHT_N               624
#define IDB_CREATELIGHT_P               625
#define IDB_CREATELIGHT_R               626
#define IDB_CURVE_ADDPOINT_N            636
#define IDB_CURVE_ADDPOINT_P            637
#define IDB_CURVE_DELETEPOINT_N         638
#define IDB_CURVE_DELETEPOINT_P         639
#define IDB_CURVE_EDITPOINT_N           640
#define IDB_CURVE_EDITPOINT_P           641
#define IDB_CURVE_FIRST_N               642
#define IDB_CURVE_FIRST_P               643
#define IDB_CURVE_INSERTPOINT_N         644
#define IDB_CURVE_INSERTPOINT_P         645
#define IDB_CURVE_LAST_N                646
#define IDB_CURVE_LAST_P                647
#define IDB_CURVE_NEXT_N                648
#define IDB_CURVE_NEXT_P                649
#define IDB_CURVE_PREV_N                650
#define IDB_CURVE_PREV_P                651
#define IDB_DIALOG_CANCEL_N             652
#define IDB_DIALOG_CANCEL_P             653
#define IDB_DIALOG_CANCEL_R             654
#define IDB_DIALOG_OK_N                 655
#define IDB_DIALOG_OK_P                 656
#define IDB_DIALOG_OK_R                 657
#define IDB_DIALOG_OK_SELECT_N          658
#define IDB_DIALOG_OK_SELECT_P          659
#define IDB_DIALOG_OK_SELECT_R          660
#define IDB_DIALOG_RESET_N              661
#define IDB_DIALOG_RESET_P              662
#define IDB_DIALOG_RESET_R              663
#define IDB_DOLLY_N                     664
#define IDB_DOLLY_P                     665
#define IDB_DOLLY_R                     666
#define IDB_EMPTY                       667
#define IDB_FLECHEB                     668
#define IDB_FLECHEB2                    669
#define IDB_FLECHEB4                    670
#define IDB_FLECHEH                     671
#define IDB_FLECHEH2                    672
#define IDB_FLECHEH4                    673
#define IDB_FOV_N                       674
#define IDB_FOV_P                       675
#define IDB_FOV_R                       676
#define IDB_GHOSTPATTERN                677
#define IDB_GRID_N                      678
#define IDB_GRID_P                      679
#define IDB_GRID_R                      680
#define IDB_ICALL1                      681
#define IDB_ICALL2                      682
#define IDB_ICALL3                      683
#define IDB_ICALL4                      684
#define IDB_ICSEL1                      685
#define IDB_ICSEL2                      686
#define IDB_ICSEL3                      687
#define IDB_ICSEL4                      688
#define IDB_LEVEL                       689
#define IDB_LEVEL2                      690
#define IDB_LEVEL4                      691
#define IDB_LOCK_N                      692
#define IDB_LOCK_P                      693
#define IDB_LOCK_R                      694
#define IDB_MAXIMIZE_N                  695
#define IDB_MAXIMIZE_P                  696
#define IDB_MINIMIZE_N                  697
#define IDB_MINIMIZE_P                  698
#define IDB_MOVE_N                      699
#define IDB_MOVE_P                      700
#define IDB_MOVE_R                      701
#define IDB_NAKED                       702
#define IDB_NAKED2                      703
#define IDB_NAKED4                      704
#define IDB_ONEPIX                      705
#define IDB_ORBIT_N                     706
#define IDB_ORBIT_P                     707
#define IDB_ORBIT_R                     708
#define IDB_ORBITAROUND_N               709
#define IDB_ORBITAROUND_P               710
#define IDB_ORBITAROUND_R               711
#define IDB_ORBITSEL_N                  712
#define IDB_ORBITSEL_P                  713
#define IDB_ORBITSEL_R                  714
#define IDB_PAN_N                       715
#define IDB_PAN_P                       716
#define IDB_PAN_R                       717
#define IDB_PARAMOP                     718
#define IDB_PICKER_N                    719
#define IDB_PICKER_P                    720
#define IDB_PICKER_R                    721
#define IDB_RESTORE_N                   722
#define IDB_RESTORE_P                   723
#define IDB_ROLL_N                      724
#define IDB_ROLL_P                      725
#define IDB_ROLL_R                      726
#define IDB_ROTATE_N                    727
#define IDB_ROTATE_P                    728
#define IDB_ROTATE_R                    729
#define IDB_SCALE_N                     730
#define IDB_SCALE_P                     731
#define IDB_SCALE_R                     732
#define IDB_SCALEEQ_N                   733
#define IDB_SCALEEQ_P                   734
#define IDB_SCALEEQ_R                   735
#define IDB_SCALEVOL_N                  736
#define IDB_SCALEVOL_P                  737
#define IDB_SCALEVOL_R                  738
#define IDB_SCENE                       739
#define IDB_SCENE_2                     740
#define IDB_SCENE_4                     741
#define IDB_SCHEMA_DELETEALL1           742
#define IDB_SCHEMA_DELETEALL2           743
#define IDB_SCHEMA_DELETEALL3           744
#define IDB_SCHEMA_DELETEALL4           745
#define IDB_SCHEMA_GRID1                746
#define IDB_SCHEMA_GRID2                747
#define IDB_SCHEMA_GRID3                748
#define IDB_SCHEMA_GRID4                749
#define IDB_SCHEMA_LINK1                750
#define IDB_SCHEMA_LINK2                751
#define IDB_SCHEMA_LINK3                752
#define IDB_SCHEMA_LINK4                753
#define IDB_SCHEMA_LOAD1                754
#define IDB_SCHEMA_LOAD2                755
#define IDB_SCHEMA_LOAD3                756
#define IDB_SCHEMA_LOAD4                757
#define IDB_SCHEMA_PROTO1               758
#define IDB_SCHEMA_PROTO2               759
#define IDB_SCHEMA_PROTO3               760
#define IDB_SCHEMA_PROTO4               761
#define IDB_SCHEMA_RESET1               762
#define IDB_SCHEMA_RESET2               763
#define IDB_SCHEMA_RESET3               764
#define IDB_SCHEMA_RESET4               765
#define IDB_SCHEMA_SCRIPT1              766
#define IDB_SCHEMA_SCRIPT2              767
#define IDB_SCHEMA_SCRIPT3              768
#define IDB_SCHEMA_SCRIPT4              769
#define IDB_SCHEMA_ZOOM1                770
#define IDB_SCHEMA_ZOOM2                771
#define IDB_SCHEMA_ZOOM3                772
#define IDB_SCHEMA_ZOOM4                773
#define IDB_SELECT_N                    774
#define IDB_SELECT_P                    775
#define IDB_SELECT_R                    776
#define IDB_SELECTFILTER_N              777
#define IDB_SELECTFILTER_P              778
#define IDB_SELECTFILTER_R              779
#define IDB_SETUP_ANIMATIONS_N          780
#define IDB_SETUP_ANIMATIONS_P          781
#define IDB_SETUP_ANIMATIONS_R          782
#define IDB_SETUP_ATTRIBUT_N            783
#define IDB_SETUP_ATTRIBUT_P            784
#define IDB_SETUP_ATTRIBUT_R            785
#define IDB_SETUP_BEHAVIORS_N           786
#define IDB_SETUP_BEHAVIORS_P           787
#define IDB_SETUP_BEHAVIORS_R           788
#define IDB_SETUP_GEOMETRY_N            789
#define IDB_SETUP_GEOMETRY_P            790
#define IDB_SETUP_GEOMETRY_R            791
#define IDB_SETUP_PARAMETER_N           792
#define IDB_SETUP_PARAMETER_P           793
#define IDB_SETUP_PARAMETER_R           794
#define IDB_SETUP_SOUND_N               795
#define IDB_SETUP_SOUND_P               796
#define IDB_SETUP_SOUND_R               797
#define IDB_SETUP_TEXTE_N               798
#define IDB_SETUP_TEXTE_P               799
#define IDB_SETUP_TEXTE_R               800
#define IDB_SETUPGRID_N                 801
#define IDB_SETUPGRID_P                 802
#define IDB_SETUPGRID_R                 803
#define IDB_SETUPRENDER_N               804
#define IDB_SETUPRENDER_P               805
#define IDB_SETUPRENDER_R               806
#define IDB_SHOWHIDE                    807
#define IDB_SHOWHIDE2                   808
#define IDB_SNAPSHOT_N                  809
#define IDB_SNAPSHOT_P                  810
#define IDB_SNAPSHOT_R                  811
#define IDB_SPINLEFT_N                  812
#define IDB_SPINLEFT_P                  813
#define IDB_SPINRIGHT_N                 814
#define IDB_SPINRIGHT_P                 815
#define IDB_SYNCRO                      834
#define IDB_USELESS                     835
#define IDB_ZOOM_N                      836
#define IDB_ZOOM_P                      837
#define IDB_ZOOM_R                      838
#define IDB_ZOOMALL_N                   839
#define IDB_ZOOMALL_P                   840
#define IDB_ZOOMALL_R                   841
#define IDB_ZOOMSEL_N                   842
#define IDB_ZOOMSEL_P                   843
#define IDB_ZOOMSEL_R                   844
#define IDB_SCHEMATIC_ZOOM4             845
#define IDB_SCHEMATIC_DELAYHIDE2        846
#define IDB_SCHEMATIC_DELAYHIDE3        847
#define IDB_SCHEMATIC_DELAYHIDE4        848
#define IDB_SCHEMATIC_DELAYSHOW1        849
#define IDB_SCHEMATIC_DELAYSHOW2        850
#define IDB_SCHEMATIC_DELAYSHOW3        851
#define IDB_SCHEMATIC_DELAYSHOW4        852
#define IDB_SCHEMATIC_DELETEALL1        853
#define IDB_SCHEMATIC_DELETEALL2        854
#define IDB_SCHEMATIC_DELETEALL3        855
#define IDB_SCHEMATIC_DELETEALL4        856
#define IDB_SCHEMATIC_GRID1             857
#define IDB_SCHEMATIC_GRID2             858
#define IDB_SCHEMATIC_GRID3             859
#define IDB_SCHEMATIC_GRID4             860
#define IDB_SCHEMATIC_HIDEOTHERS1       861
#define IDB_SCHEMATIC_HIDEOTHERS2       862
#define IDB_SCHEMATIC_HIDEOTHERS3       863
#define IDB_SCHEMATIC_HIDEOTHERS4       864
#define IDB_SCHEMATIC_LINK1             865
#define IDB_SCHEMATIC_LINK2             866
#define IDB_SCHEMATIC_LINK3             867
#define IDB_SCHEMATIC_LINK4             868
#define IDB_SCHEMATIC_LOAD1             869
#define IDB_SCHEMATIC_LOAD2             870
#define IDB_SCHEMATIC_LOAD3             871
#define IDB_SCHEMATIC_LOAD4             872
#define IDB_SCHEMATIC_PROTO1            873
#define IDB_SCHEMATIC_PROTO2            874
#define IDB_SCHEMATIC_PROTO3            875
#define IDB_SCHEMATIC_PROTO4            876
#define IDB_SCHEMATIC_RESETZOOM1        877
#define IDB_SCHEMATIC_RESETZOOM2        878
#define IDB_SCHEMATIC_RESETZOOM3        879
#define IDB_SCHEMATIC_RESETZOOM4        880
#define IDB_SCHEMATIC_SCRIPT1           881
#define IDB_SCHEMATIC_SCRIPT2           882
#define IDB_SCHEMATIC_SCRIPT3           883
#define IDB_SCHEMATIC_SCRIPT4           884
#define IDB_SCHEMATIC_TRACE1            885
#define IDB_SCHEMATIC_TRACE2            886
#define IDB_SCHEMATIC_TRACE3            887
#define IDB_SCHEMATIC_TRACE4            888
#define IDB_SCHEMATIC_UNHIDEALL1        889
#define IDB_SCHEMATIC_UNHIDEALL2        890
#define IDB_SCHEMATIC_UNHIDEALL3        891
#define IDB_SCHEMATIC_UNHIDEALL4        892
#define IDB_SCHEMATIC_ZOOM1             893
#define IDB_SCHEMATIC_ZOOM2             894
#define IDB_SCHEMATIC_ZOOM3             895
#define IDB_SCHEMATIC_DELAYHIDE1        896
#define IDB_STATUS_PLAY1                907
#define IDB_STATUS_PLAY2                908
#define IDB_STATUS_PLAY3                909
#define IDB_STATUS_PLAY4                910
#define IDB_STATUS_RESTORE_IC1          911
#define IDB_STATUS_RESTORE_IC2          912
#define IDB_STATUS_RESTORE_IC3          913
#define IDB_STATUS_STEP1                914
#define IDB_STATUS_STEP2                915
#define IDB_STATUS_STEP3                916
#define IDB_CAPTURE1                    917
#define IDB_CAPTURE2                    918
#define IDB_CAPTURE3                    919
#define IDB_TAKE1                       921
#define IDB_TAKE2                       922
#define IDB_TAKE3                       923
#define IDB_SNAPSHOT_EMPTYBOX           929
#define IDB_CLOSE_BUTTON3               930
#define IDB_CLEAR_BUTTON2               931
#define IDB_CLEAR_BUTTON3               932
#define IDB_CLOSE_BUTTON1               933
#define IDB_CLOSE_BUTTON2               934
#define IDB_CLEAR_BUTTON1               935
#define IDB_APPLY3                      937
#define IDB_APPLY2                      938
#define IDB_APPLY1                      939
#define IDB_SETUP_ATTRIBUT_CREATEATTRIB 940
#define IDB_SETUP_ATTRIBUT_CREATEATTRIB2 941
#define IDB_SETUP_ATTRIBUT_CREATEATTRIB4 942
#define IDB_SETUP_ATTRIBUT_CREATECATEGORY 943
#define IDB_SETUP_ATTRIBUT_CREATECATEGORY2 944
#define IDB_SETUP_ATTRIBUT_CREATECATEGORY4 945
#define IDB_SETUP_ATTRIBUT_DELETECATEGORY 946
#define IDB_SETUP_ATTRIBUT_DELETECATEGORY2 947
#define IDB_SETUP_ATTRIBUT_DELETECATEGORY4 948
#define IDI_EMITTER                     949
#define IDI_RECEIVER                    950
#define IDI_SHORTCUT                    951
#define IDI_EMITTERACTIVE               952
#define IDB_MINIMIZEALL_4               952
#define IDI_RECEIVERACTIVE              953
#define IDB_MINIMIZEALL_2               953
#define IDI_SHORTCUT3                   954
#define IDB_MINIMIZEALL_3               954
#define IDI_SHORTCUT4                   955
#define IDB_MINIMIZEALL_1               955
#define IDI_EMPTYSCRIPTSNAPSHOT         959
#define IDI_SETTINGS                    960
#define IDB_PROFILER                    961
#define IDI_LOCALSHORTCUT               961
#define IDB_PROFILER1                   961
#define IDB_SCHEMATIC_GRID2_4           962
#define IDI_VARIABLEIO                  962
#define IDB_SCHEMATIC_GRID2_2           963
#define IDI_SHORCUTSOURCE               963
#define IDB_SCHEMATIC_GRID2_3           964
#define IDI_HASCUSTOMEDITBOX            964
#define IDB_SCHEMATIC_GRID2_1           965
#define IDI_DATAARRAY                   965
#define IDI_OBJECTGRID                  966
#define IDB_SCHEMATIC_PRIORITY4         969
#define IDB_SCHEMATIC_PRIORITY2         970
#define IDB_SCHEMATIC_PRIORITY3         971
#define IDB_SCHEMATIC_PRIORITY1         972
#define IDB_LEVEL_EXPAND3               973
#define IDB_LEVEL_COLAPSE2              974
#define IDB_LEVEL_COLAPSE3              975
#define IDB_LEVEL_EXPAND                976
#define IDB_LEVEL_EXPAND2               977
#define IDB_LEVEL_COLAPSE               978
#define IDB_BACK                        979
#define IDB_BACK2                       980
#define IDB_FORWARD                     981
#define IDB_FORWARD2                    982
#define IDB_HOME                        983
#define IDB_HOME2                       984
#define IDB_SHOWHIDESCRIPTS4            985
#define IDB_SHOWHIDEPOINTS2             986
#define IDB_SHOWHIDEPOINTS3             987
#define IDB_SHOWHIDEPOINTS4             988
#define IDB_SHOWHIDESCRIPTS1            989
#define IDB_SHOWHIDESCRIPTS2            990
#define IDB_SHOWHIDESCRIPTS3            991
#define IDB_SHOWHIDEPOINTS1             992
#define IDB_SCHEMATIC_CROSS1            993
#define IDB_SCHEMATIC_CROSS2            994
#define IDB_SCHEMATIC_ROUND1            995
#define IDB_SCHEMATIC_ROUND2            996
#define IDB_SCHEMATIC_CROSS3            997
#define IDB_SCHEMATIC_CROSS4            998
#define IDB_SCHEMATIC_ROUND3            999
#define IDB_SCHEMATIC_ROUND4            1000
#define IDB_SHOWHIDEDELAY1              1002
#define IDB_SHOWHIDEDELAY2              1003
#define IDB_SHOWHIDEDELAY3              1004
#define IDB_SHOWHIDEDELAY4              1005
#define IDB_REALDEBUG4                  1006
#define IDB_REALDEBUG2                  1007
#define IDC_SCENE                       1008
#define IDB_REALDEBUG3                  1008
#define IDC_PLACE                       1009
#define IDB_REALDEBUG1                  1009
#define IDC_LINK                        1010
#define IDI_WORKSET                     1011
#define IDC_TYPE                        1012
#define IDC_NAME                        1013
#define IDC_VALUE                       1014
#define IDC_OPTYPE                      1016
#define IDC_I1TYPE                      1017
#define IDC_I1PICK                      1018
#define IDC_I2TYPE                      1019
#define IDC_I2PICK                      1020
#define IDC_STATICMESSAGE               1020
#define IDC_OTYPE                       1021
#define IDC_CLEARLOG                    1021
#define IDC_OPICK                       1022
#define IDB_CREATEWORKSET4              1022
#define IDC_HIDE                        1023
#define IDB_CREATEARRAY2                1023
#define IDB_CREATEARRAY4                1024
#define IDB_CREATEGROUP                 1025
#define IDB_CREATEGROUP2                1026
#define IDC_LISTBOX                     1027
#define IDB_CREATEGROUP4                1027
#define IDC_OBJECTNAME                  1028
#define IDB_CREATEPLACE                 1028
#define IDC_DELETEMESH                  1029
#define IDB_CREATEPLACE2                1029
#define IDC_DELETEMATERIAL              1030
#define ID_APPLY                        1030
#define IDB_CREATEPLACE4                1030
#define IDC_DELETETEXTURE               1031
#define IDB_CREATESCENE                 1031
#define IDB_CREATESCENE2                1032
#define IDB_CREATESCENE4                1033
#define IDB_CREATEWORKSET2              1034
#define IDB_CREATEWORKSET               1035
#define IDB_CREATEARRAY                 1036
#define IDC_LIST1                       1037
#define IDB_CREATESCRIPT4               1037
#define IDB_CREATESCRIPT2               1038
#define IDB_CREATESCRIPT                1039
#define IDB_SHTEXTURE4                  1041
#define IDB_SHMATERIAL2                 1042
#define IDB_SHMATERIAL3                 1043
#define IDB_SHMATERIAL4                 1044
#define IDB_SHMESH1                     1045
#define IDB_SHMESH2                     1046
#define IDB_SHMESH3                     1047
#define IDB_SHMESH4                     1048
#define IDB_SHTEXTURE1                  1049
#define IDC_STATICTOTAL                 1050
#define IDB_SHTEXTURE2                  1050
#define IDB_SHTEXTURE3                  1051
#define IDB_SHMATERIAL1                 1052
#define IDB_ADDCATEGORY1                1053
#define IDB_ADDCATEGORY2                1054
#define IDB_ADDCATEGORY3                1055
#define IDB_ADDCATEGORY4                1056
#define IDB_COPY1                       1057
#define IDB_COPY2                       1058
#define IDB_COPY3                       1059
#define IDB_COPY4                       1060
#define IDB_PASTE1                      1061
#define IDB_PASTE2                      1062
#define IDB_PASTE3                      1063
#define IDB_PASTE4                      1064
#define IDB_REMOVECOLUMN_P              1068
#define IDB_ADDCOLUMN_R                 1069
#define IDB_ADDCOLUMN_P                 1070
#define IDB_ADDLINE_N                   1071
#define IDB_ADDLINE_R                   1072
#define IDB_ADDLINE_P                   1073
#define IDB_REMOVECOLUMN_N              1074
#define IDB_REMOVECOLUMN_R              1075
#define IDB_ADDCOLUMN_N                 1076
#define IDB_DEBUGTOOLS4                 1077
#define IDB_DEBUGTOOLS2                 1078
#define IDB_DEBUGTOOLS3                 1079
#define IDB_DEBUGTOOLS1                 1080
#define IDB_ADDBREAKPOINT1              1081
#define IDB_ADDBREAKPOINT2              1082
#define IDB_ADDBREAKPOINT3              1083
#define IDB_BREAKPOINTLIST1             1084
#define IDB_BREAKPOINTLIST2             1085
#define IDB_BREAKPOINTLIST3             1086
#define IDB_DEBUGSTEP1                  1087
#define IDB_DEBUGSTEP2                  1088
#define IDB_DEBUGSTEP3                  1089
#define IDB_GOTOREACHEDBREAKPOINT1      1090
#define IDB_GOTOREACHEDBREAKPOINT2      1091
#define IDB_GOTOREACHEDBREAKPOINT3      1092
#define IDB_GOTOBREAKPOINT1             1093
#define IDB_BEHAVIORSTACK3              1094
#define IDB_REMOVEALLBREAKPOINTS2       1095
#define IDB_REMOVEALLBREAKPOINTS3       1096
#define IDB_REMOVEBREAKPOINT1           1097
#define IDB_REMOVEBREAKPOINT2           1098
#define IDB_REMOVEBREAKPOINT3           1099
#define IDB_REMOVE1                     1100
#define IDB_REMOVE2                     1101
#define IDB_REMOVE3                     1102
#define IDB_BEHAVIORSTACK1              1103
#define IDB_BEHAVIORSTACK2              1104
#define IDB_REMOVEALLBREAKPOINTS1       1105
#define IDB_LEAVEBEHAVIOR3              1106
#define IDB_LEAVEBEHAVIOR2              1107
#define IDB_LEAVEBEHAVIOR1              1108
#define IDB_BREAKPOINTREACHED2          1109
#define IDB_BREAKPOINTREACHED1          1110
#define IDB_CLEAR1                      1111
#define IDB_CLEAR2                      1112
#define IDB_CLEAR3                      1113
#define IDB_DOWN1                       1114
#define IDB_DOWN2                       1115
#define IDB_DOWN3                       1116
#define IDB_UP1                         1117
#define IDB_UP2                         1118
#define IDB_UP3                         1119
#define IDB_GOTOBREAKPOINT3             1120
#define IDB_GOTOBREAKPOINT2             1121
#define IDI_BREAKPOINT                  1122
#define IDB_SCHEMATIC_HIDEALL1          1124
#define IDB_SCHEMATIC_HIDEALL2          1125
#define IDB_SCHEMATIC_HIDEALL3          1126
#define IDB_SCHEMATIC_HIDEALL4          1127
#define IDB_SCHEMATIC_HIDESELECTED1     1128
#define IDB_SCHEMATIC_HIDESELECTED2     1129
#define IDB_SCHEMATIC_HIDESELECTED3     1130
#define IDB_SCHEMATIC_HIDESELECTED4     1131
#define IDB_SCHEMATIC_HIDEUNSELECTED1   1132
#define IDB_SCHEMATIC_HIDEUNSELECTED2   1133
#define IDB_SCHEMATIC_HIDEUNSELECTED3   1134
#define IDB_SCHEMATIC_HIDEUNSELECTED4   1135
#define IDB_SCHEMATIC_SHOWALL1          1136
#define IDB_SCHEMATIC_SHOWALL4          1137
#define IDB_SCHEMATIC_SHOWALL3          1138
#define IDB_SCHEMATIC_SHOWALL2          1139
#define IDB_REFRESH3                    1140
#define IDB_GOSETUP2                    1141
#define IDB_GOSETUP3                    1142
#define IDB_REFRESH1                    1143
#define IDB_REFRESH2                    1144
#define IDB_GOSETUP1                    1145
#define IDB_CREATEGRID_P                1146
#define IDB_CREATEGRID_N                1147
#define IDB_CREATEGRID_R                1148
#define IDB_CROSS_SELECT_P              1149
#define IDB_CROSS_SELECT_R              1150
#define IDB_CROSS_SELECT_N              1151
#define IDB_STRICT_SELECT_N             1152
#define IDB_STRICT_SELECT_R             1153
#define IDB_STRICT_SELECT_P             1154
#define IDB_ADDTEXTURE_N                1155
#define IDB_ADDTEXTURE_R                1156
#define IDI_SCHEMATIC_LOCAL             1156
#define IDB_ADDTEXTURE_P                1157
#define IDB_PICKER_GRAY_N               1158
#define IDB_PICKER_GRAY_R               1159
#define IDB_PICKER_GRAY_P               1160
#define IDB_REMOVESLOT_N                1161
#define IDB_REMOVESLOT_R                1162
#define IDB_REMOVESLOT_P                1163
#define IDB_FILTER_ALL_N                1164
#define IDB_FILTER_ALL_R                1165
#define IDB_FILTER_ALL_P                1166
#define IDB_FILTER_DELETE_N             1167
#define IDB_FILTER_DELETE_R             1168
#define IDB_FILTER_DELETE_P             1169
#define IDB_FILTER_GOTO_N               1170
#define IDB_FILTER_GOTO_R               1171
#define IDB_FILTER_GOTO_P               1172
#define IDB_FILTER_INVERT_N             1173
#define IDB_FILTER_INVERT_R             1174
#define IDB_FILTER_INVERT_P             1175
#define IDB_FILTER_NONE_N               1176
#define IDB_FILTER_NONE_R               1177
#define IDB_FILTER_NONE_P               1178
#define IDB_CURVE_ADDPOINT_R            1179
#define IDB_CURVE_DELETEPOINT_R         1180
#define IDB_CURVE_EDITPOINT_R           1181
#define IDB_CURVE_FIRST_R               1182
#define IDB_CURVE_INSERTPOINT_R         1183
#define IDB_CURVE_LAST_R                1184
#define IDB_CURVE_NEXT_R                1185
#define IDB_CURVE_PREV_R                1186
#define IDB_AXISX_OFF                   1187
#define IDB_AXISY_OFF                   1188
#define IDB_AXISZ_OFF                   1189
#define IDB_AXISXZ_OFF                  1190
#define IDB_LTDKPATTERN                 1191
#define IDB_SOUNDSETUP_PAUSE1           1192
#define IDB_SOUNDSETUP_PAUSE2           1193
#define IDB_SOUNDSETUP_PLAY1            1194
#define IDB_SOUNDSETUP_PLAY2            1195
#define IDB_SOUNDSETUP_STOP1            1196
#define IDB_SOUNDSETUP_STOP2            1197
#define IDB_SOUNDSETUP_STOP4            1198
#define IDB_SOUNDSETUP_STOP3            1199
#define IDB_TL_ADDTIMELINE1             1200
#define IDB_TL_ADDTIMELINE2             1201
#define IDB_TL_ADDTIMELINE3             1202
#define IDB_TL_ADDTIMELINE4             1203
#define IDB_TL_MIN1                     1204
#define IDB_TL_MIN2                     1205
#define IDB_TL_MIN3                     1206
#define IDB_TL_MIN4                     1207
#define IDB_TL_MS1                      1208
#define IDB_TL_MS2                      1209
#define IDB_TL_MS3                      1210
#define IDB_TL_MS4                      1211
#define IDB_TL_S1                       1212
#define IDB_TL_S2                       1213
#define IDB_TL_S3                       1214
#define IDB_TL_S4                       1215
#define IDB_ATTRIBUTE_CLOSE3            1217
#define IDB_ATTRIBUTE_CLOSE2            1218
#define IDB_ATTRIBUTE_CLOSE1            1219
#define IDB_ATTRIBUTE_MORE3             1220
#define IDB_ATTRIBUTE_ADDSELECTED2      1221
#define IDB_ATTRIBUTE_ADDSELECTED3      1222
#define IDB_ATTRIBUTE_CREATE1           1223
#define IDB_ATTRIBUTE_CREATE2           1224
#define IDB_ATTRIBUTE_CREATE3           1225
#define IDB_ATTRIBUTE_LESS1             1226
#define IDB_ATTRIBUTE_LESS2             1227
#define IDB_ATTRIBUTE_LESS3             1228
#define IDB_ATTRIBUTE_MORE1             1229
#define IDB_ATTRIBUTE_MORE2             1230
#define IDB_ATTRIBUTE_ADDSELECTED1      1231
#define IDB_SETUP_SETASUNIT3            1232
#define IDB_SETUP_OPENFILE2             1233
#define IDB_SETUP_OPENFILE3             1234
#define IDB_SETUP_SETASUNIT1            1235
#define IDB_SETUP_SETASUNIT2            1236
#define IDB_SETUP_OPENFILE1             1237
#define IDB_SNAP_R                      1238
#define IDB_SNAP_P                      1239
#define IDB_SNAP_N                      1240
#define IDB_PATHMANAGER_UP3             1242
#define IDB_PATHMANAGER_ADDPATH2        1243
#define IDB_PATHMANAGER_ADDPATH3        1244
#define IDB_PATHMANAGER_DELETEPATH1     1245
#define IDB_PATHMANAGER_DELETEPATH2     1246
#define IDB_PATHMANAGER_DELETEPATH3     1247
#define IDB_PATHMANAGER_DOWN1           1248
#define IDB_PATHMANAGER_DOWN2           1249
#define IDB_PATHMANAGER_DOWN3           1250
#define IDB_PATHMANAGER_UP1             1251
#define IDB_PATHMANAGER_UP2             1252
#define IDB_PATHMANAGER_ADDPATH1        1253
#define IDB_HIERARCHY_3                 1254
#define IDB_HIERARCHY_2                 1255
#define IDB_HIERARCHY_1                 1256
#define IDB_HIERARCHY_4                 1257
#define IDB_GRID3D_1                    1258
#define IDB_GRID3D_2                    1259
#define IDB_GRID3D_3                    1260
#define IDB_ANCHOR_1                    1261
#define IDB_ANCHOR_2                    1262
#define IDB_ANCHOR_3                    1263
#define IDB_ANCHOR_4                    1264
#define IDB_ANCHOR_5                    1265
#define IDB_ANCHOR_6                    1266
#define IDB_ANCHOR_7                    1267
#define IDB_ANCHOR_8                    1268
#define IDB_ANCHOR_9                    1269
#define IDB_FLY_1                       1270
#define IDB_FLY_2                       1271
#define IDB_FLY_3                       1272
#define IDB_SETUP_BLACKOPENFILE1        1273
#define IDB_SETUP_BLACKOPENFILE2        1274
#define IDB_SETUP_BLACKOPENFILE3        1275
#define IDB_CREATEFRAME3D_R             1276
#define IDB_CREATEFRAME3D_P             1277
#define IDB_CREATEFRAME3D_N             1278
#define IDB_3DVIEWSIZE_N                1279
#define IDB_3DVIEWSIZE_R                1280
#define IDB_3DVIEWSIZE_P                1281
#define IDB_SCHEMATIC_MESSAGEHELP4      1290
#define IDB_SCHEMATIC_MESSAGEHELP2      1291
#define IDB_SCHEMATIC_MESSAGEHELP3      1292
#define IDB_SCHEMATIC_MESSAGEHELP1      1293
#define IDB_ABOUTNEMO                   1295
#define IDI_BEHAVIORLOCKED              1296
#define IDB_RESIZE                      1297
#define IDI_PARAMETER                   1297
#define IDB_SIMPLIFIED4                 1298
#define IDB_SIMPLIFIED2                 1299
#define IDB_SIMPLIFIED3                 1300
#define IDB_SIMPLIFIED1                 1301
#define IDB_LOCK4                       1302
#define IDB_LOCK2                       1303
#define IDB_LOCK3                       1304
#define IDB_LOCK1                       1305
#define IDB_DEFAULTLINKDELAY3           1306
#define IDB_DEFAULTLINKDELAY2           1307
#define IDB_DEFAULTLINKDELAY1           1308
#define IDB_CREATEPORTAL_R              1309
#define IDI_SCHEMATIC_IC                1309
#define IDB_CREATEPORTAL_P              1310
#define IDB_CREATEPORTAL_N              1311
#define IDB_SEARCH3                     1312
#define IDB_SEARCH2                     1313
#define IDB_SEARCH1                     1314
#define IDI_NEMOEXCLAMATION             1317
#define IDI_NEMOWARNING                 1318
#define IDI_NEMOERROR                   1319
#define IDI_NEMOQUESTION                1320
#define IDI_NEMO                        1321
#define IDI_NEMOSTOP                    1322
#define IDI_BUILDINGBLOCK               1323
#define IDI_COMMENT                     1324
#define IDB_CREATEMATERIALS1            1324
#define IDB_CREATEMATERIALS2            1325
#define IDI_PARAMETEROPERATION          1326
#define IDB_CREATEMATERIALS3            1326
#define IDB_CREATETEXTURE1              1327
#define IDI_OUTPUTPARAMETER             1327
#define IDB_CREATETEXTURE2              1328
#define IDI_INPUT                       1328
#define IDB_CREATETEXTURE3              1329
#define IDI_OUTPUT                      1329
#define IDI_INPUTPARAMETER              1330
#define IDI_PATCHMESH                   1331
#define IDB_LINKERROR3                  1333
#define IDB_LINKERROR2                  1334
#define IDB_LINKERROR1                  1335
#define IDI_ICON1                       1336
#define IDB_ONEPIXA                     1336
#define IDI_SCHEMATIC_ACTIVE            1337
#define IDB_SYNCROA                     1337
#define IDB_ACREATEPORTAL_R             1338
#define IDB_ACREATEPORTAL_P             1339
#define IDB_ACREATEPORTAL_N             1340
#define IDB_BOMB2                       1341
#define IDB_BOMB3                       1342
#define IDB_PROFILER2                   1343
#define IDB_PROFILER3                   1344
#define IDB_FINDPREV3                   1345
#define IDB_FIND2                       1346
#define IDB_FIND3                       1347
#define IDB_FINDNEXT1                   1348
#define IDB_FINDNEXT2                   1349
#define IDB_FINDNEXT3                   1350
#define IDB_FINDPREV1                   1351
#define IDB_FINDPREV2                   1352
#define IDB_FIND1                       1353
#define IDB_SL_SR                       1354
#define IDB_SL_L                        1355
#define IDB_SL_LR                       1356
#define IDB_SL_S                        1357
#define IDB_CUBEMAP                     1360
#define IDB_TREEMODE1                   1361
#define IDB_TREEMODE2                   1362
#define IDB_TREEMODE3                   1363
#define IDB_TREEMODE4                   1364
#define IDB_RESTORE1                    1365
#define IDB_RESTORE2                    1366
#define IDB_RESTORE3                    1367
#define IDB_RESTORE4                    1368
#define IDB_RESTOREALL1                 1369
#define IDB_RESTOREALL2                 1370
#define IDB_RESTOREALL3                 1371
#define IDB_RESTOREALL4                 1372
#define IDB_SAVEFILE1                   1373
#define IDB_SAVEFILE2                   1374
#define IDB_SAVEFILE3                   1375
#define IDB_ACTION2                     1378
#define IDB_ACTION4                     1379
#define IDI_VARAPP                      1380
#define IDB_ACTION                      1380
#define IDI_VARCOMPO                    1381
#define IDI_VARNATIVECOMPO              1382
#define IDB_UNDO2                       1382
#define IDI_SCHEMATIC_VARIABLE          1383
#define IDB_REDO1                       1383
#define IDI_STATEMENT                   1384
#define IDB_REDO2                       1384
#define IDI_COMMENTSELECTED             1385
#define IDB_UNDO1                       1385
#define IDI_VSL                         1386
#define IDB_UNDO3                       1386
#define IDB_REDO3                       1387
#define IDI_POINTCLOUD                  1387
#define IDB_BEHAVIORERROR3              1388
#define IDB_BEHAVIORERROR2              1389
#define IDB_BEHAVIORERROR1              1390
#define ID_F1_A                         32772
#define ID_F1_B                         32773
#define ID_F2_C                         32774
#define ID_F2_D                         32775
#define ID_F2_E                         32776
#define ID_A                            32777
#define ID_LAYOUT_CREATEEDITOR          32783
#define ID_LAYOUT_CREATEVIEW            32784
#define ID_ORGANIZER_CREATEEDITOR       32785
#define ID_ORGANIZER_CREATEVIEW         32786
#define ID_SCHEMATIC_CREATEEDITOR       32787
#define ID_SCHEMATIC_CREATEVIEW         32788
#define ID_GEOMETRY_CREATEEDITOR        32789
#define ID_GEOMETRY_CREATEVIEW          32790
#define ID_CAMERA_CREATEEDITOR          32791
#define ID_CAMERA_CREATEVIEW            32792
#define ID_CLEARALL                     32793
#define ID_LOADLEVEL                    32794
#define ID_SAVELEVEL                    32795
#define ID_LEVEL_CREATEEDITOR           32798
#define ID_HTML_CREATEEDITOR            32799
#define ID_IMPORTASPLACE                32800
#define ID_IMPORTFILEASCHARACTER        32801
#define ID_IMPORT                       32802
#define ID_IMPORTFILEASPLACE            32803
#define ID_SNAPSHOT_CREATEEDITOR        32804
#define ID_EDIT_EMPTYCLIPBOARD          32805
#define ID_ACCEL_CREATEBEHAVIOR         32810
#define ID_ACCEL_LINK                   32811
#define ID_SHOWALLDLG                   32812
#define ID_ACCEL_NEXTFRAME              32813
#define IDS_LEVELVIEW_NEW_PLACE         61446
#define IDS_LEVELVIEW_NEW_SCRIPT        61447
#define IDS_LEVELVIEW_SHOWHIDETOGGLE    61448
#define IDS_LEVELVIEW_NAMEEDIT          61449
#define IDS_LEVELVIEW_SELECTIONGROUP    61450
#define IDS_LEVELVIEW_SELECTFILTER      61451
#define IDS_LEVELVIEW_SETSELECTEDCOND   61452
#define IDS_LEVELVIEW_SETGLOBALCOND     61453
#define IDS_STATUSBAR_UNDO              61454
#define IDS_STATUSBAR_REDO              61455
#define IDS_STATUSBAR_UNDOLIST          61456
#define IDS_STATUSBAR_CURRENTSCENE      61457
#define IDS_STATUSBAR_SELECTION         61458
#define IDS_STATUSBAR_ACTION            61459
#define IDS_STATUSBAR_X                 61460
#define IDS_STATUSBAR_Y                 61461
#define IDS_STATUSBAR_Z                 61462
#define IDS_STATUSBAR_BOMB              61463
#define IDS_STATUSBAR_ERRORLOG          61464
#define IDS_STATUSBAR_CAMFOV            61465
#define IDS_STATUSBAR_FPS               61466
#define IDS_STATUSBAR_INITIAL           61467
#define IDS_STATUSBAR_STEPONE           61468
#define IDS_STATUSBAR_PLAYPAUSE         61469
#define IDS_NOSELECTION                 61470
#define IDS_NOACTION                    61471

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        1388
#define _APS_NEXT_COMMAND_VALUE         32814
#define _APS_NEXT_CONTROL_VALUE         1031
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
